<?php

function cipher_menu() {
  $items = array();
  $items['cipher'] = array(
    'title' => 'Ceasar Cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function cipher_form() {
  $form['shift_amount'] = array(
    '#title' => t('Shift Amount'),
    '#type' => 'textfield',
    '#description' => t('Enter the amount of characters you want to shift your message.')
  );
  $form['shift_direction'] = array(
    '#title' => t('Shift Direction'),
    '#description' => t('Choose whether you would like to shift "left" or "right".'),
  );
  $form['input'] = array(
    '#title' => t('Message to Encode'),
    '#type' => 'textfield',
    '#description' => t('Enter the messsage you would like to encrypt.')
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Encrypt Now!',
  );
  return $form;
}
